### ISSUE TITLE
帳號資訊和金鑰資訊

### ISSUE THREAD

**Issue by PeterWolf-tw** [PeterWolf-tw/NTNU_TextProcessing_2021#4]
https://github.com/PeterWolf-tw/NTNU_TextProcessing_2021/blob/9994df3264c92a50dedf1314adbeafaf052ce9fb/week09/week09_Peter.py#L46

請加上存取你的帳號資訊和金鑰資訊的機制，如果留空的話，預設是讀取公用字數。
而公用字數不一定跑得完作業需求。

**Comment by KazumiLine** [comment]
好的，原來如此，我改完了，謝謝老師

**Comment by PeterWolf-tw** [comment]
Good, thahnks.
