### ISSUE TITLE
Week09作業請益

### ISSUE THREAD

**Issue by 40775012H** [PeterWolf-tw/NTNU_TextProcessing_2021#5]
不好意思，如果方便的話，想請問Peter組在getData函式中n==1取得地點，append i[0][2]的邏輯是什麼？還有n==3取得人名，tempDICT[j[2]]的地方也是。若CSIE112組知道的話，可以麻煩你們幫忙解答一下嗎？
        因為主函式中有讀取../account.info的這行指令，不清楚如何執行程式碼來觀察過程，我看了幾天都似懂非懂。

**Comment by PeterWolf-tw** [comment]
#18 行
https://github.com/PeterWolf-tw/NTNU_TextProcessing_2021/blob/31668a15c4f1faabeb4c3b8cc71c5f1b6283a150/week09/week09_Peter.py#L18

看起來像是把三個功能都寫在 getData() 裡，只是用 n 這個變數來選擇要啟動哪一個功能。

**Comment by KaoZhai** [comment]
@40775012H 所以是想問我們 Peter 那組的 code 嗎？那不是我們寫的@@

**Comment by 40775012H** [comment]
你好，因為看到你們兩組有一行指令的寫法相似，不知道功能是否為一樣?我自己看完覺得這應該是要判斷，在什麼狀況下要將「欲抓取的詞彙」加進列表(不重複)。 
是在`def tourblogfunct(inputSTR):`裡的第55行的`	placelist.append( item[0][2] )`和第62行的` locationlist.append( item[0][2] )`

**Comment by KaoZhai** [comment]
上面的 if(temlist != None) 跟 if item != [] 是確認該 list 跟裡面的元素不為空，如果成立就將其元素抓出來並放入結果列表。
會打 [0][2] 是因為 apicut 後回傳的元素是一個一個的 list，而元素的第 0 項是該辭彙起始位置，第 1 項是該辭彙的結束位置，第 2 項才是我們要的詞。

**Comment by 40775012H** [comment]
原來是這樣，感謝！
