### ISSUE TITLE
請你開一個資料夾，把作業和所需的檔案放進去好嗎？

### ISSUE THREAD

**Issue by PeterWolf-tw** [PeterWolf-tw/NTNU_TextProcessing_2021#6]
https://github.com/PeterWolf-tw/NTNU_TextProcessing_2021/blob/5f8c70366ed56a4a992a2f6767a9193ffcac070c/week10/week10_Peter.py#L1

**Comment by KazumiLine** [comment]
老師對不起 我們重開資料夾了。

**Comment by PeterWolf-tw** [comment]
Good job. 
Thanks.
