### ISSUE TITLE
Articut level 3 出錯

### ISSUE THREAD

**Issue by sophie8909** [PeterWolf-tw/NTNU_TextProcessing_2021#7]
https://github.com/PeterWolf-tw/NTNU_TextProcessing_2021/blob/e9f697247c8b5544daa62f196993584538bd892e/week12/CSIE112/week12_CSIE112.py#L78

錯誤訊息如下，如果使用 lv2 則可正常運作
![Error msg](https://user-images.githubusercontent.com/34826797/119136897-c808f380-ba72-11eb-9c75-8bfc67714884.png)

**Comment by sophie8909** [comment]
附上 lv2 執行後結果
![lv2 result](https://user-images.githubusercontent.com/34826797/119137333-4b2a4980-ba73-11eb-9152-003ea98c7ad8.png)

**Comment by PeterWolf-tw** [comment]
Hi Sophie8989, 

請更新一下您的 ArticutAPI 試試看。
```pip3 install ArticutAPI --upgrade```
或是
```pip3 install ArticutAPI -U```

thx.
pw.

**Comment by sophie8909** [comment]
> Hi Sophie8989,
> 
> 請更新一下您的 ArticutAPI 試試看。
> `pip3 install ArticutAPI --upgrade`
> 或是
> `pip3 install ArticutAPI -U`
> 
> thx.
> pw.

解決了，謝謝。
